function main()
% main 热学实验虚拟仿真系统主界面
% 运行此函数启动系统（响应式布局）

% 关闭已存在的主窗口
existingFig = findobj('Tag', core.AppConfig.MainWindowTag);
if ~isempty(existingFig)
    close(existingFig);
end

% ==================== 创建主窗口 ====================
fig = uifigure('Name', [core.AppConfig.AppName ' ' core.AppConfig.Version], ...
    'Tag', core.AppConfig.MainWindowTag, ...
    'Position', ui.StyleConfig.centerWindow(ui.StyleConfig.MainWindowSize), ...
    'Color', ui.StyleConfig.BackgroundColor, ...
    'Resize', 'on');

% ==================== 主布局（垂直分割）====================
mainGrid = uigridlayout(fig, [3, 1], ...
    'RowHeight', {ui.StyleConfig.HeaderHeight, '1x', ui.StyleConfig.FooterHeight}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.BackgroundColor, ...
    'Padding', [0, 0, 0, 0], ...
    'RowSpacing', 0);

% ==================== 顶部区域：Logo和标题 ====================
topPanel = uipanel(mainGrid, ...
    'BackgroundColor', ui.StyleConfig.PrimaryColor, ...
    'BorderType', 'none');
topPanel.Layout.Row = 1;
topPanel.Layout.Column = 1;

% 顶部内部布局
topGrid = uigridlayout(topPanel, [1, 4], ...
    'ColumnWidth', {200, '1x', 100, 20}, ...
    'RowHeight', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.PrimaryColor, ...
    'Padding', [15, 20, 15, 20]);

% Logo
logoPath = ui.StyleConfig.getImagePath('logo.png');
if isfile(logoPath)
    logoImg = uiimage(topGrid, ...
        'ImageSource', logoPath, ...
        'ScaleMethod', 'fit');
    logoImg.Layout.Row = 1;
    logoImg.Layout.Column = 1;
end

% 标题区域
titlePanel = uipanel(topGrid, ...
    'BackgroundColor', ui.StyleConfig.PrimaryColor, ...
    'BorderType', 'none');
titlePanel.Layout.Row = 1;
titlePanel.Layout.Column = 2;

% 实验须知按钮
guideBtn = uibutton(topGrid, ...
    'Text', core.AppConfig.GuideButtonText, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeSubheader, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'FontColor', ui.StyleConfig.PrimaryColor, ...
    'ButtonPushedFcn', @(~,~) showLabGuidelines());
guideBtn.Layout.Row = 1;
guideBtn.Layout.Column = 3;

titleGrid = uigridlayout(titlePanel, [2, 1], ...
    'RowHeight', {40, 25}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.PrimaryColor, ...
    'Padding', [10, 15, 0, 15], ...
    'RowSpacing', 2);

% 系统标题
titleLabel = uilabel(titleGrid, ...
    'Text', core.AppConfig.AppName, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeLarge, ...
    'FontWeight', 'bold', ...
    'FontColor', ui.StyleConfig.TextLight, ...
    'VerticalAlignment', 'center');
titleLabel.Layout.Row = 1;
titleLabel.Layout.Column = 1;

% 副标题
subtitleLabel = uilabel(titleGrid, ...
    'Text', core.AppConfig.AppSubtitle, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeButton, ...
    'FontColor', ui.StyleConfig.TextLight, ...
    'VerticalAlignment', 'top');
subtitleLabel.Layout.Row = 2;
subtitleLabel.Layout.Column = 1;

% ==================== 中部区域：实验选择 ====================
contentPanel = uipanel(mainGrid, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'BorderType', 'none');
contentPanel.Layout.Row = 2;
contentPanel.Layout.Column = 1;

% 内容区布局
contentGrid = uigridlayout(contentPanel, [2, 1], ...
    'RowHeight', {50, '1x'}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'Padding', [50, 20, 50, 20], ...
    'RowSpacing', ui.StyleConfig.ComponentSpacing);

% 实验选择提示
selectLabel = uilabel(contentGrid, ...
    'Text', core.AppConfig.SelectExpPrompt, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeHeader, ...
    'FontWeight', 'bold', ...
    'FontColor', ui.StyleConfig.TextPrimary, ...
    'HorizontalAlignment', 'center');
selectLabel.Layout.Row = 1;
selectLabel.Layout.Column = 1;

% 实验卡片网格（2列3行）
cardGrid = uigridlayout(contentGrid, [3, 2], ...
    'RowHeight', {'1x', '1x', '1x'}, ...
    'ColumnWidth', {'1x', '1x'}, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'Padding', [20, 10, 20, 10], ...
    'RowSpacing', 20, ...
    'ColumnSpacing', 30);
cardGrid.Layout.Row = 2;
cardGrid.Layout.Column = 1;

% ==================== 实验按钮配置 ====================
expList = core.AppConfig.ExperimentList;

% 创建实验卡片（2列3行布局）
for i = 1:size(expList, 1)
    row = ceil(i / 2);
    col = mod(i - 1, 2) + 1;

    % 创建实验卡片
    createExperimentCard(cardGrid, row, col, ...
        expList{i, 1}, expList{i, 2}, expList{i, 3}, fig);
end

% ==================== 底部区域：版权信息 ====================
footerGrid = uigridlayout(mainGrid, [1, 1], ...
    'RowHeight', {'1x'}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.BackgroundColor, ...
    'Padding', [0, 5, 0, 5]);
footerGrid.Layout.Row = 3;
footerGrid.Layout.Column = 1;

footerLabel = uilabel(footerGrid, ...
    'Text', ['© ' core.AppConfig.CopyrightYear ' ' core.AppConfig.AppName ' ' core.AppConfig.Version ' | ' core.AppConfig.Organization], ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeSmall, ...
    'FontColor', ui.StyleConfig.TextSecondary, ...
    'HorizontalAlignment', 'center');
footerLabel.Layout.Row = 1;
footerLabel.Layout.Column = 1;
end

% ==================== 辅助函数 ====================
function createExperimentCard(parentGrid, row, col, expNum, expName, expFunc, fig)
% 创建实验卡片

% 卡片面板
cardPanel = uipanel(parentGrid, ...
    'BackgroundColor', ui.StyleConfig.BackgroundColor, ...
    'BorderType', 'line', ...
    'BorderWidth', 1, ...
    'HighlightColor', ui.StyleConfig.PrimaryColor);
cardPanel.Layout.Row = row;
cardPanel.Layout.Column = col;

% 卡片内部布局
cardInnerGrid = uigridlayout(cardPanel, [3, 2], ...
    'RowHeight', {35, '1x', 40}, ...
    'ColumnWidth', {'1x', ui.StyleConfig.ButtonWidthSmall}, ...
    'BackgroundColor', ui.StyleConfig.BackgroundColor, ...
    'Padding', [15, 10, 15, 10], ...
    'RowSpacing', 5, ...
    'ColumnSpacing', ui.StyleConfig.ComponentSpacing);

% 实验编号
numLabel = uilabel(cardInnerGrid, ...
    'Text', expNum, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeHeader, ...
    'FontWeight', 'bold', ...
    'FontColor', ui.StyleConfig.PrimaryColor);
numLabel.Layout.Row = 1;
numLabel.Layout.Column = [1, 2];

% 实验名称
nameLabel = uilabel(cardInnerGrid, ...
    'Text', expName, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeSubheader - 1, ...
    'FontWeight', 'bold', ...
    'FontColor', ui.StyleConfig.TextPrimary, ...
    'WordWrap', 'on', ...
    'VerticalAlignment', 'top');
nameLabel.Layout.Row = 2;
nameLabel.Layout.Column = [1, 2];

% 占位（左下）
spacer = uilabel(cardInnerGrid, 'Text', ''); %#ok<NASGU>
spacer.Layout.Row = 3;
spacer.Layout.Column = 1;

% 进入实验按钮（右下）
enterBtn = uibutton(cardInnerGrid, ...
    'Text', core.AppConfig.EnterExpBtnText, ...
    'ButtonPushedFcn', @(~,~) launchExperiment(expFunc, fig));
enterBtn.Layout.Row = 3;
enterBtn.Layout.Column = 2;
ui.StyleConfig.applyButtonStyle(enterBtn, 'primary');
end

function launchExperiment(expName, fig)
% 启动指定实验

% 检查主窗口是否有效
if isempty(fig) || ~isvalid(fig)
    return;
end

% 关闭实验须知窗口（如果打开）
existingGuide = findobj('Tag', core.AppConfig.GuideWindowTag);
if ~isempty(existingGuide)
    close(existingGuide);
end

% 支持的实验列表
validExperiments = core.AppConfig.ExperimentList(:, 3);

% 检查实验是否在支持列表中
if ~ismember(expName, validExperiments)
    uialert(fig, ['实验模块 "' expName '" ' core.AppConfig.ExpDevMsg], ...
        core.AppConfig.AlertTitleInfo, 'Icon', 'info');
    return;
end

try
    % 动态构造类名并实例化
    className = ['experiments.' expName];
    exp = feval(className);
    exp.show();

    % 关闭主窗口
    if isvalid(fig)
        close(fig);
    end
catch ME
    % 实验模块加载失败，显示错误
    uialert(fig, [core.AppConfig.ExpLoadFailMsg ME.message], ...
        core.AppConfig.AlertTitleError, 'Icon', 'error');
end
end

function showLabGuidelines()
% 显示实验规程窗口（精简版）

% 关闭已存在的实验须知窗口
existingFig = findobj('Tag', core.AppConfig.GuideWindowTag);
if ~isempty(existingFig)
    close(existingFig);
end

% 创建规程窗口
guideFig = uifigure('Name', core.AppConfig.GuideWindowTitle, ...
    'Tag', core.AppConfig.GuideWindowTag, ...
    'Position', ui.StyleConfig.centerWindow(ui.StyleConfig.GuideWindowSize), ...
    'Color', ui.StyleConfig.PanelColor, ...
    'Resize', 'off');

% 主布局
mainGrid = uigridlayout(guideFig, [2, 1], ...
    'RowHeight', {'1x', 55}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'Padding', [20, 15, 20, 10]);

% 内容区域（使用 grid 布局）
contentGrid = uigridlayout(mainGrid, [1, 1], ...
    'RowHeight', {'1x'}, ...
    'ColumnWidth', {'1x'}, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'Padding', [30, 20, 30, 10]);
contentGrid.Layout.Row = 1;
contentGrid.Layout.Column = 1;

% 规程内容（精简版）
guidelineText = sprintf(['【热学实验操作规程】\n\n' ...
    '【1】准备\n' ...
    '进入实验室前，应预习实验，掌握操作原理，明确目的、步骤及注意事项。\n\n' ...
    '【2】热学计量仪器\n' ...
    '使用前明确测量规则、读数方法、单位和量程。确认系统处于热平衡状态后再读数。\n\n' ...
    '【3】加热安全\n' ...
    '检查电源接触是否牢靠，设备是否接地。避免大功率快速加热，防止电路烧毁或火灾。\n\n' ...
    '【4】归整\n' ...
    '实验结束后关闭电源，整理仪器放回原位，保持实验室整洁。']);

% 显示规程内容
guideLabel = uilabel(contentGrid, ...
    'Text', guidelineText, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeCaption, ...
    'FontColor', ui.StyleConfig.TextPrimary, ...
    'WordWrap', 'on', ...
    'VerticalAlignment', 'top');
guideLabel.Layout.Row = 1;
guideLabel.Layout.Column = 1;

% 关闭按钮区域（响应式居中）
btnGrid = uigridlayout(mainGrid, [1, 3], ...
    'ColumnWidth', {'1x', ui.StyleConfig.ButtonWidthSmall, '1x'}, ...
    'RowHeight', {35}, ...
    'BackgroundColor', ui.StyleConfig.PanelColor, ...
    'Padding', [0, 10, 0, 10]);
btnGrid.Layout.Row = 2;
btnGrid.Layout.Column = 1;

closeBtn = uibutton(btnGrid, ...
    'Text', core.AppConfig.GuideConfirmText, ...
    'FontName', ui.StyleConfig.FontFamily, ...
    'FontSize', ui.StyleConfig.FontSizeCaption, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', ui.StyleConfig.PrimaryColor, ...
    'FontColor', ui.StyleConfig.TextLight, ...
    'ButtonPushedFcn', @(~,~) close(guideFig));
closeBtn.Layout.Row = 1;
closeBtn.Layout.Column = 2;
end
